# ---------------
# 自定义主题颜色
# 注意：颜色值必须用双引号，如"#000"，否则可能会导致错误！
# ---------------
# theme_color:
#   enable: true
#   main: "#49B1F5"
#   paginator: "#00C4B6"
#   button_hover: "#FF7242"
#   text_selection: "#00C4B6"
#   link_color: "#858585"
#   hr_color: "#A4D8FA"
#   tag_start_color: "#A4D8FA"
#   tag_end_color: "#1B9EF3"
#   header_text_color: "#EEEEEE"
#   footer_text_color: "#EEEEEE"

# 主菜单导航
menu:
  主页: /
  归档: /archives
  分类: /categories
  标签: /tags
  友链: /friends
  关于我: /about

# 网站图标
# ---------------
favicon: /melody-favicon.ico

# PWA
# See https://github.com/JLHwung/hexo-offline
# ---------------
pwa:
  enable: false
  manifest: /manifest.json
  # 如果你不想麻烦，就忽略下面的事情
  # See https://realfavicongenerator.net/
  # theme_color: "#49B1F5"
  # apple_touch_icon: /apple-touch-icon.png
  # favicon_32_32: /favicon-32x32.png
  # favicon_16_16: /favicon-16x16.png
  # mask_icon: /safari-pinned-tab.svg

# 代码高亮主题
# ---------------
highlight_theme: default # default/darker/pale night/light/ocean

# 代码换行
# ---------------
# code_word_wrap: true or false

# 社交图标
# 在站点顶部设置一些你的社交图标。格式是图标名 前缀: url
# 查看 fontawesome 网站中的 icon_name。
# 并且你需要自己添加`fa`或`fab`前缀。
# ---------------
social:
  github fa: https://github.com/staoran
  rss fa: /atom.xml

# Algolia search
# ---------------
algolia_search:
  enable: false
  hits:
    per_page: 10

# 本地搜索
# 详情请看文档: https://molunerfinn.com/hexo-theme-melody-doc/third-party-support.html#local-search
# ---------------
local_search:
  enable: true

# MathJax
# 详情请看文档: https://molunerfinn.com/hexo-theme-melody-doc/third-party-support.html#mathjax
# ---------------
mathjax:
  enable: false
  cdn: https://cdn.jsdelivr.net/npm/mathjax/MathJax.js?config=TeX-AMS-MML_HTMLorMML

# KaTeX
# 详情请看文档: https://molunerfinn.com/hexo-theme-melody-doc/third-party-support.html#katex
# ---------------
katex:
  enable: false
  cdn:
    css: https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.css
  hide_scrollbar: true

# 烟花
# ---------------
fireworks: false

# 分析
# ---------------
baidu_analytics:

google_analytics:

# Tencent_analytics ID
tencent_analytics:

# 在 <head> 中加载的样式表
# ---------------
stylesheets:
  - /css/index.css
# 在正文末尾加载的脚本
# ---------------
scripts:
  - /js/utils.js
  - /js/fancybox.js
  - /js/sidebar.js
  - /js/copy.js
  - /js/fireworks.js
  - /js/transition.js
  - /js/scroll.js
  - /js/head.js

# 第三方库的cdn
# ---------------
cdn:
  css:
    fontawesome: https://cdn.jsdelivr.net/npm/font-awesome@latest/css/font-awesome.min.css
    # fontawesomeV5: https://use.fontawesome.com/releases/v5.3.1/css/all.css
  js:
    anime: https://cdn.jsdelivr.net/npm/animejs@latest/anime.min.js
    jquery: https://cdn.jsdelivr.net/npm/jquery@latest/dist/jquery.min.js
    fancybox: https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@latest/dist/jquery.fancybox.min.js
    velocity: https://cdn.jsdelivr.net/npm/velocity-animate@latest/velocity.min.js
    velocity-ui: https://cdn.jsdelivr.net/npm/velocity-ui-pack@latest/velocity.ui.min.js

# 头像
# ---------------
avatar:

# 顶部图
# ---------------
top_img: false # true false 或 img 的 url

# 顶部图高度
# ---------------
top_img_height: 60 # 最佳范围：60 - 100

# 文章相关项
# 这个选项是用来显示文章的相关信息的。
# ---------------
post_meta:
  date_type: created # or updated 文章日期是创建日或者更新日
  categories: true # or false 是否显示分类
  tags: true # or false 是否显示标签

# 详情请看文档: https://molunerfinn.com/hexo-theme-melody-doc/additional-package-support.html#word-counting
wordcount:
  enable: true

toc:
  enable: true # or false
  number: true # or false. 版本v1.5.6新增

# 文章版权
# ---------------
post_copyright:
  enable: true
  license: CC BY-NC-SA 4.0 # 协议名称
  license_url: https://creativecommons.org/licenses/by-nc-sa/4.0/ # 协议说明地址

# 自动节选: https://molunerfinn.com/hexo-theme-melody-doc/theme-config.html#auto-excerpt
auto_excerpt:
  enable: true
  length: 150

# slide
# For reveal.js config, see https://github.com/hakimel/reveal.js#configuration
slide:
  separator: ---
  separator_vertical: --
  charset: utf-8
  theme: black
  codeTheme: monokai
  # optional
  mouseWheel: false
  transition: slide
  transitionSpeed: default
  parallaxBackgroundImage: ""
  parallaxBackgroundSize: ""
  parallaxBackgroundHorizontal: null
  parallaxBackgroundVertical: null
  loop: false
  autoSlide: false
  controlsBackArrows: "faded"
  controlsLayout: "bottom-right" # Determines where controls appear, "edges" or "bottom-right"
  progress: true
  showNotes: false
  autoPlayMedia: false
  backgroundTransition: "fade"

# 文章相关二维码
# ---------------
QR_code:
  - itemlist:
      img: https://xxxx1.jpg
      text: 支付宝打赏
  - itemlist:
      img: https://xxxx2.jpg
      text: 微信打赏

# 文章广告区
# ---------------
adv:
  enable: false
  info: # 你想展示的内容

# 分享系统
# ---------------
addThis:
  enable: false
  #pubid:

# sharejs:
# enable: false
# disabled_sites:

# 评论系统
# ---------------
disqus:
  enable: false
  #shortname:
  #count:

# laibili:
# enable: false
# uid:

# gitment
# enable: false
# owner:
# repo:
# client_id:
# client_secret:

# gitalk:
#   enable: false
#   client_id:
#   client_secret:
#   repo:
#   owner:
#   admin:

# valine comment system. https://valine.js.org
# valine:
#   enable: false # if you want use valine,please set this value is true
#   appId:  # leancloud application app id
#   appKey:  # leancloud application app key
#   notify: false # valine mail notify (true/false) https://github.com/xCss/Valine/wiki
#   verify: false # valine verify code (true/false)
#   recordip: false # whether record commentor's ip (true/false)
#   pageSize: 10 # comment list page size
#   avatar: mm # gravatar style https://valine.js.org/#/avatar
#   lang: zh-cn # i18n: zh-cn/en
#   placeholder: Just go go # valine comment input placeholder(like: Please leave your footprints )
#   guest_info: nick,mail,link #valine comment header inf

# vssue:
# enable: false # Set to true to enable
# platform: github-v4
# owner:
# repo:
# clientId:
# clientSecret: # only required for some of the platforms
# autoCreateIssue: false # Auto create issue on platform (github/...)
# baseURL: "" # For self-hosted gitlab/bitbucket only, see here: https://vssue.js.org/options/#baseurl
# perPage: 10 # How much comment/page
# labels: 'Vssue'

# 展示你站点起始时间的选项。它位于页面的最底部。
# ---------------
since: 2022

# 页脚自定义文本，
# 通常你可以在这里写ICP备案号、码云声明文本等。支持HTML。
# 如果你配置成 hitokoto 那么底部文字将会生成随机的谚语，可以查看例子：https://blog.k1yoshi.com/
# ---------------
# footer_custom_text: Hi, welcome to my <a href="https://molunerfinn.com">blog</a>!
footer_custom_text: hitokoto

ICP:
  enable: false
  #text:

# busuanzi count for PV / UV in site
busuanzi:
  # count values only if the other configs are false
  enable: true
  # custom uv span for the whole site
  site_uv: true
  site_uv_header: <i class="fa fa-user"></i>
  site_uv_footer:
  # custom pv span for the whole site
  site_pv: true
  site_pv_header: <i class="fa fa-eye"></i>
  site_pv_footer:
  # custom pv span for one page only
  page_pv: true
  page_pv_header: <i class="fa fa-file"></i>
  page_pv_footer:

# 彩带
# See: https://github.com/hustcc/ribbon.js
canvas_ribbon:
  enable: false
  size: 150
  alpha: 0.6
  zIndex: -1
  click_to_change: false

# 友链
# ---------------
links_title: Links # 配置友链的标题文字
links:
  Molunerfinn: https://molunerfinn.com # 名称：URL
  GitHub: https://github.com/staoran
  码云: https://gitee.com/taomail
  Hexo官网: https://hexo.io

# Follow Me Button
follow:
  enable: true
  url: "https://github.com/staoran"
  text: "Follow Me"

# 侧边栏展示控制
# all: 所有的页面都会自动展示侧边栏
# index: 只有首页会自动展示侧边栏
# post: 只有文章页会自动展示侧边栏
# index-none: 只有首页不会自动展示侧边栏
# post-none: 只有文章页不会自动展示侧边栏
# hidden: 所有的页面都不会自动展示侧边栏
sidebar_display: post # all/index/post/index-none/post-none/hidden

# 谷歌广告
# ---------------
google_adsense:
  enable: false
  js: //pagead2.googlesyndication.com/pagead/js/adsbygoogle.js
  client: ca-pub-...........
  enable_page_level_ads: true

# Google 站长工具验证设置
# See: https://www.google.com/webmasters/
google_site_verification:

# Bing 站长工具验证设置
# See: https://www.bing.com/webmaster/
bing_site_verification:

# Yandex 站长工具验证设置
# See: https://webmaster.yandex.ru/
#yandex_site_verification:

# Baidu 站长工具验证设置
# See: https://ziyuan.baidu.com/site/
baidu_site_verification:

# 360 站长工具验证设置
# see http://zhanzhang.so.com/
qihu_site_verification:

# 避免百度改造
disable_baidu_transformation: true

# 404 Page SubTitle
404Text:
